/* ==========================================================================
   Dragon Ball Clash Action TCG — 2D SpriteSheet Animation Catalog
   Unified 16/32-bit arcade TCG attack animations & character spritesheet registry
   ========================================================================== */

export const ANIMATION_TYPES = {
  PHYSICAL_ATTACK: 'PHYSICAL_ATTACK',
  KI_BLAST: 'KI_BLAST',
  SUPER_KAMEHAMEHA: 'SUPER_KAMEHAMEHA',
  GENKI_DAMA: 'GENKI_DAMA',
  FINAL_FLASH: 'FINAL_FLASH',
  DEATH_BEAM: 'DEATH_BEAM',
  COUNTER: 'COUNTER',
  DEFENSE_BARRIER: 'DEFENSE_BARRIER',
  ZVANISH: 'ZVANISH',
  KI_CHARGE: 'KI_CHARGE',
  KAIOKEN: 'KAIOKEN',
  LIFE_BREAK: 'LIFE_BREAK'
};

export const ANIMATION_CATALOG = {
  [ANIMATION_TYPES.PHYSICAL_ATTACK]: {
    id: 'physical_attack',
    name: 'Dragon Strike Punch',
    spriteSheetUrl: 'assets/spritesheets/fx/punch_sheet.png',
    frameWidth: 64,
    frameHeight: 64,
    totalFrames: 8,
    fps: 14,
    blendMode: 'screen',
    durationMs: 600,
    shakeClass: 'shake-sm',
    soundKey: 'attack',
    impactFrame: true,
    overlayType: 'target_center'
  },
  [ANIMATION_TYPES.KI_BLAST]: {
    id: 'ki_blast',
    name: 'Ki Blast Barrage',
    spriteSheetUrl: 'assets/spritesheets/fx/ki_blast_sheet.png',
    frameWidth: 64,
    frameHeight: 64,
    totalFrames: 10,
    fps: 16,
    blendMode: 'screen',
    durationMs: 700,
    shakeClass: 'shake-md',
    soundKey: 'kiBlast',
    impactFrame: false,
    overlayType: 'projectile_trajectory'
  },
  [ANIMATION_TYPES.SUPER_KAMEHAMEHA]: {
    id: 'super_kamehameha',
    name: 'Super Kamehameha Beam',
    spriteSheetUrl: 'assets/spritesheets/fx/kamehameha_sheet.png',
    frameWidth: 64,
    frameHeight: 64,
    totalFrames: 8,
    fps: 12,
    blendMode: 'screen',
    durationMs: 2000,
    shakeClass: 'shake-heavy',
    soundKey: 'kamehameha',
    color: '#00f2fe',
    quote: 'KA... ME... HA... ME... HAAA!',
    cutinDurationMs: 900,
    impactFrame: true,
    skipTargetVfx: true, // Central beam renderer handles battlefield strike
    overlayType: 'fullscreen_beam'
  },
  [ANIMATION_TYPES.GENKI_DAMA]: {
    id: 'genki_dama',
    name: 'Spirit Bomb (Genki Dama)',
    spriteSheetUrl: 'assets/spritesheets/fx/genki_dama_sheet.png',
    frameWidth: 64,
    frameHeight: 64,
    totalFrames: 10,
    fps: 10,
    blendMode: 'lighten',
    durationMs: 2500,
    shakeClass: 'shake-heavy',
    soundKey: 'genkidama',
    color: '#1fa2ff',
    quote: 'TODOS DA TERRA, ME DÊEM SUA ENERGIA!',
    cutinDurationMs: 1100,
    impactFrame: true,
    skipTargetVfx: true,
    overlayType: 'fullscreen_bomb'
  },
  [ANIMATION_TYPES.FINAL_FLASH]: {
    id: 'final_flash',
    name: 'Final Flash',
    spriteSheetUrl: 'assets/spritesheets/fx/final_flash_sheet.png',
    frameWidth: 64,
    frameHeight: 64,
    totalFrames: 10,
    fps: 12,
    blendMode: 'color-dodge',
    durationMs: 2200,
    shakeClass: 'shake-heavy',
    soundKey: 'beamClash',
    color: '#ffd700',
    quote: 'FINAL... FLAAAASH!',
    cutinDurationMs: 900,
    impactFrame: true,
    skipTargetVfx: true,
    overlayType: 'fullscreen_beam'
  },
  [ANIMATION_TYPES.DEATH_BEAM]: {
    id: 'death_beam',
    name: 'Death Beam',
    spriteSheetUrl: 'assets/spritesheets/fx/death_beam_sheet.png',
    frameWidth: 64,
    frameHeight: 64,
    totalFrames: 10,
    fps: 14,
    blendMode: 'screen',
    durationMs: 1200,
    shakeClass: 'shake-md',
    soundKey: 'counter',
    color: '#ff0055',
    quote: 'DANCE PARA MIM, MACACO!',
    cutinDurationMs: 750,
    impactFrame: true,
    overlayType: 'target_center'
  },
  [ANIMATION_TYPES.COUNTER]: {
    id: 'counter',
    name: 'Z-Counter Deflect',
    spriteSheetUrl: 'assets/spritesheets/fx/punch_sheet.png',
    frameWidth: 64,
    frameHeight: 64,
    totalFrames: 8,
    fps: 16,
    blendMode: 'color-dodge',
    durationMs: 600,
    shakeClass: 'shake-sm',
    soundKey: 'counter',
    impactFrame: true,
    overlayType: 'target_center'
  },
  [ANIMATION_TYPES.DEFENSE_BARRIER]: {
    id: 'defense_barrier',
    name: 'Barrier Shield',
    spriteSheetUrl: 'assets/spritesheets/fx/barrier_sheet.png',
    frameWidth: 64,
    frameHeight: 64,
    totalFrames: 8,
    fps: 12,
    blendMode: 'screen',
    durationMs: 800,
    shakeClass: 'shake-sm',
    soundKey: 'shieldBreak',
    impactFrame: false,
    overlayType: 'target_center'
  },
  [ANIMATION_TYPES.ZVANISH]: {
    id: 'zvanish',
    name: 'Z-Vanish Teleport',
    spriteSheetUrl: 'assets/spritesheets/fx/vanish_sheet.png',
    frameWidth: 64,
    frameHeight: 64,
    totalFrames: 8,
    fps: 16,
    blendMode: 'screen',
    durationMs: 500,
    shakeClass: 'shake-sm',
    soundKey: 'zvanish',
    impactFrame: false,
    overlayType: 'target_center'
  },
  [ANIMATION_TYPES.KI_CHARGE]: {
    id: 'ki_charge',
    name: 'Super Saiyan Ki Charge',
    spriteSheetUrl: 'assets/spritesheets/fx/barrier_sheet.png',
    frameWidth: 64,
    frameHeight: 64,
    totalFrames: 8,
    fps: 12,
    blendMode: 'screen',
    durationMs: 1200,
    shakeClass: 'shake-md',
    soundKey: 'charge',
    impactFrame: false,
    overlayType: 'target_center'
  },
  [ANIMATION_TYPES.KAIOKEN]: {
    id: 'kaioken',
    name: 'Kaioken Burst',
    spriteSheetUrl: 'assets/spritesheets/fx/punch_sheet.png',
    frameWidth: 64,
    frameHeight: 64,
    totalFrames: 8,
    fps: 14,
    blendMode: 'color-dodge',
    durationMs: 900,
    shakeClass: 'shake-md',
    soundKey: 'awaken',
    impactFrame: true,
    overlayType: 'target_center'
  },
  [ANIMATION_TYPES.LIFE_BREAK]: {
    id: 'life_break',
    name: 'Life Point Shatter',
    spriteSheetUrl: 'assets/spritesheets/fx/punch_sheet.png',
    frameWidth: 64,
    frameHeight: 64,
    totalFrames: 8,
    fps: 14,
    blendMode: 'screen',
    durationMs: 900,
    shakeClass: 'shake-heavy',
    soundKey: 'hit',
    color: '#ff0033',
    impactFrame: true,
    overlayType: 'hp_bar'
  }
};
